name: cosc480
dependencies:
  - python=3.7
  - jupyter
  - nltk
  - pandas
  - pip
  - pip:
      - graphviz
      - networkx
      - spacy==2.1
      - neuralcoref
      - plac==0.9.6
      - stanfordnlp
      - git+https://github.com/stanfordnlp/stanza.git
